### ISSUE TITLE
Create a script to flood network with transactions

### ISSUE THREAD

**Issue by slavasn** [bloqly/bloqly#19]
Transaction example:

```bash
curl -X POST \
-H 'Content-Type: application/json' \
-d '
{
    "origin": "58BF325AF01CCC78265EB715C1EB10EEA455905D4B50C2AC6541950D97DF8607",
    "passphrase": "root password",
    "destination": "5CA1EEF9AA50625F3B7AC637D35655174CAA2C4FAB559B294D6E7C924C9AA6D4",
    "args": [
        {
            "type": "BIGINT",
            "value": "1"
        }
    ]
}
' http://localhost:9901/api/v1/data/transactions 
```

Would be really nice to have a way to pass parameters with number of threads and interval between transactions

**Comment by quantumblockz** [comment]
Here is a test script to flood the network with transactions. Includes ability to specify thread count and time interval between actions in seconds.
[https://github.com/quantumblockz/bloqly_tests/blob/master/floodtxs.py](url)
